/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Control.database;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Compra;
import modelo.CompraDB;
import modelo.Derivados;
import modelo.DerivadosDB;
import modelo.DetalleCompra;
import modelo.Productos;
import modelo.ProductosDB;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;



/**
 *
 * @author yopri
 */
public class sistema extends javax.swing.JFrame {

    /**
     * Creates new form sistema
     */
    Productos pro = new Productos();
    ProductosDB pdb = new ProductosDB();
    Derivados der = new Derivados();
    DerivadosDB ddb = new DerivadosDB();
    DefaultTableModel modelo = new DefaultTableModel();
    TableRowSorter trs = new TableRowSorter();
    ArrayList codigos = new ArrayList();
    Compra c = new Compra();
    CompraDB cdb = new CompraDB();
    DetalleCompra cd = new DetalleCompra();
    int item;
    float totalpagar;
    DefaultTableModel tmp;
    public sistema() {
        initComponents();
        String rol;
        this.setLocationRelativeTo(null);
        setSize(1120, 700);
        Toolkit tk=Toolkit.getDefaultToolkit();
        Dimension d=tk.getScreenSize();
        setLocation((d.width-getSize().width)/2,(d.height-getSize().height)/2);
        jlbFecha.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jlbUsuario.setText(""+database.name);
        jlbRol.setText(""+rol());
        if(database.rol==3){
         btnCombos.setEnabled(false);
         btnAdministracion.setEnabled(false);
        }
        jtfCodigo.requestFocus();
        jtfBase.setText("1");
        jtfBase.setEnabled(false);
        
        pdb.ConsulatarProducto(jcbProductos);
        pdb.ConsulatarCodigos(codigos);
        AutoCompleteDecorator.decorate(jcbProductos );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        btnProductos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnAdministracion = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlbRol = new javax.swing.JLabel();
        btnCombos = new javax.swing.JButton();
        jlbUsuario = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jlbFecha = new javax.swing.JLabel();
        jtp = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfDetalle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbUnidad = new javax.swing.JComboBox<>();
        jtfPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfBase = new javax.swing.JTextField();
        jcbBase = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableP = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfPrecioD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfDetalleD = new javax.swing.JTextField();
        jtfCodigoD = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfNombreD = new javax.swing.JTextField();
        btnAgregarD = new javax.swing.JButton();
        btnEditarD = new javax.swing.JButton();
        btnEliminarD = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableD = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jcbProductos = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtfPrecioC = new javax.swing.JTextField();
        jtfCantidadC = new javax.swing.JTextField();
        btnAgregarC = new javax.swing.JButton();
        jtfEliminarC = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtCompra = new javax.swing.JTable();
        bntRegC = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jtfNombreC = new javax.swing.JTextField();
        jtfCodigoC = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtfTotalC = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jlbSeccion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 101, -1));

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 101, -1));

        btnCompras.setText("Compras");
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 101, -1));

        btnAdministracion.setText("Administración");
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 101, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Rol:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jlbRol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbRol.setText("rol");
        jPanel1.add(jlbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        btnCombos.setText("Granel");
        btnCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCombos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 101, -1));

        jlbUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbUsuario.setText("usuario");
        jPanel1.add(jlbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 150, 515));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 640, 69, -1));

        jlbFecha.setText("fecha");
        getContentPane().add(jlbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 164, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setText("Codigo");
        jPanel3.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, -1));

        jLabel9.setText("Cantidad");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jtp.addTab("tab2", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });
        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyTyped(evt);
            }
        });
        jPanel2.add(jtfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 129, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, -1, -1));

        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNombreKeyPressed(evt);
            }
        });
        jPanel2.add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, 125, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Detalle");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, -1, -1));

        jtfDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDetalleKeyPressed(evt);
            }
        });
        jPanel2.add(jtfDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 191, 125, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Unidad de medida");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, -1, -1));

        jcbUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Kg - Kilogramo", "U - Unidad", " " }));
        jcbUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUnidadActionPerformed(evt);
            }
        });
        jcbUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbUnidadKeyPressed(evt);
            }
        });
        jPanel2.add(jcbUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 125, -1));

        jtfPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPrecioKeyPressed(evt);
            }
        });
        jPanel2.add(jtfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 125, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Base");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jtfBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfBaseKeyPressed(evt);
            }
        });
        jPanel2.add(jtfBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 125, -1));

        jcbBase.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcbBaseStateChanged(evt);
            }
        });
        jcbBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBaseActionPerformed(evt);
            }
        });
        jPanel2.add(jcbBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 100, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 100, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 90, -1));

        jtableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Detalle", "UDM", "Precio", "Base", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablePMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableP);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 11, 760, 480));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Productos");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Precio");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jtp.addTab("tab1", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Producto");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Precio");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));
        jPanel4.add(jtfPrecioD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 110, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Codigo granel");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel4.add(jtfDetalleD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 110, -1));
        jPanel4.add(jtfCodigoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Detalle");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel4.add(jtfNombreD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, -1));

        btnAgregarD.setText("Agregar");
        btnAgregarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 100, -1));

        btnEditarD.setText("Editar");
        btnEditarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 100, -1));

        btnEliminarD.setText("Eliminar");
        btnEliminarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 90, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Granel");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jtableD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Codigo granel", "Nombre granel", "Detalle", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtableD);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 750, 460));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Nombre granel");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jcbProductos.setEditable(true);
        jcbProductos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbProductosItemStateChanged(evt);
            }
        });
        jcbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProductosActionPerformed(evt);
            }
        });
        jPanel4.add(jcbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, -1));

        jtp.addTab("tab3", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Compras");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Total:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Codigo");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Cantidad");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        jPanel5.add(jtfPrecioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 260, -1));

        jtfCantidadC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCantidadCKeyPressed(evt);
            }
        });
        jPanel5.add(jtfCantidadC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 260, -1));

        btnAgregarC.setText("Agregar");
        btnAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCActionPerformed(evt);
            }
        });
        jPanel5.add(btnAgregarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 260, -1));

        jtfEliminarC.setText("Eliminar");
        jtfEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEliminarCActionPerformed(evt);
            }
        });
        jPanel5.add(jtfEliminarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 250, -1));

        jtCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtCompra);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 530, 440));

        bntRegC.setText("Registrar Compra");
        bntRegC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegCActionPerformed(evt);
            }
        });
        jPanel5.add(bntRegC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 260, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Nombre");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel5.add(jtfNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 260, -1));

        jtfCodigoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoCKeyPressed(evt);
            }
        });
        jPanel5.add(jtfCodigoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 260, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Precio");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jtfTotalC.setEditable(false);
        jPanel5.add(jtfTotalC, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 160, -1));

        jtp.addTab("tab4", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jtp.addTab("tab5", jPanel6);
        jtp.addTab("tab6", jPanel7);

        getContentPane().add(jtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 930, 580));

        jlbSeccion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbSeccion.setText("Punto de venta e Inventario");
        getContentPane().add(jlbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 400, -1));

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        jtp.setSelectedIndex(3);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
        
        jtp.setSelectedIndex(3);
        LimpiarCompra();
    }//GEN-LAST:event_btnComprasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        vista.Login ventana = new vista.Login();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed
        // TODO add your handling code here:
        vista.Administracion ventana = new vista.Administracion();
        ventana.setVisible(true);
        this.dispose();
        jtp.setSelectedIndex(5);
    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        jtp.setSelectedIndex(1);
        LimpiarProductos();
        LimpiarTable();
        try {
            ListarProductos();
        } catch (SQLException ex) {
            Logger.getLogger(sistema.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProductosActionPerformed

    private void jtfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtfNombre.requestFocus();
        }
    }//GEN-LAST:event_jtfCodigoKeyPressed

    private void jtfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtfDetalle.requestFocus();
        }
    }//GEN-LAST:event_jtfNombreKeyPressed

    private void jtfDetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDetalleKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jcbUnidad.requestFocus();
        }
    }//GEN-LAST:event_jtfDetalleKeyPressed

    private void jcbUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbUnidadActionPerformed

    private void jcbUnidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbUnidadKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtfPrecio.requestFocus();
        }
    }//GEN-LAST:event_jcbUnidadKeyPressed

    private void jtfPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnAgregar.requestFocus();
        }
    }//GEN-LAST:event_jtfPrecioKeyPressed

    private void jtfBaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBaseKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnAgregar.requestFocus();
        }
    }//GEN-LAST:event_jtfBaseKeyPressed

    private void jcbBaseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcbBaseStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBaseStateChanged

    private void jcbBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBaseActionPerformed
        // TODO add your handling code here:
        if(jcbBase.isSelected())
        {
            jtfBase.setEnabled(true);
        }
        else{
            jtfBase.setEnabled(false);
        }
    }//GEN-LAST:event_jcbBaseActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        int resultado=0;
        float base;
        int cdproducto;
        String nombre;
        String detalle;
        int unidad;
        float precio;
        if(Numeros(jtfBase.getText())){
            if(Numeros(jtfBase.getText()) && Float.parseFloat(jtfBase.getText())<=1 && Float.parseFloat(jtfBase.getText())>0){
                base = Float.parseFloat(jtfBase.getText());
                pro.setBase(base);
            }
            else{
                JOptionPane.showMessageDialog(this, "Ingrese solo valores en el rango 0.1Kg - 1Kg");
                resultado =1;
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese solo valores numericos como valor base");
            resultado =1;
        }
        if(jtfNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para el producto");
            resultado =1;
        }
        else{
            nombre = jtfNombre.getText();
            pro.setName(nombre);
        }
        if(Numeros(jtfCodigo.getText())){
            if(Float.parseFloat(jtfCodigo.getText())!=0){
                cdproducto = Integer.parseInt(jtfCodigo.getText());
                pro.setCd(cdproducto);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "El codigo no es valido");
            resultado =1;
        }
        if(jcbUnidad.getSelectedItem().equals("-")){
            JOptionPane.showMessageDialog(this, "Ingrese una unidad de medida");
            resultado =1;
        }
        else{
            unidad = jcbUnidad.getSelectedIndex();
            pro.setUdm(unidad);
        }
        if(Numeros(jtfPrecio.getText())){
            if(!jtfPrecio.getText().equals("")){
                precio = Float.parseFloat(jtfPrecio.getText());
                pro.setPrecio(precio);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese un precio correcto");
            resultado =1;
        }
        detalle = jtfDetalle.getText();
        pro.setDetalle(detalle);
        if(resultado==0){
                boolean res = pdb.agregarP(pro);
                if(res){
                     JOptionPane.showMessageDialog(this, "Producto agregado correctamente");
             LimpiarTable();
                LimpiarProductos();
            try {
                ListarProductos();
            } catch (SQLException ex) {
                System.out.println(""+ex.toString());
            }
                }
                else{
                              JOptionPane.showMessageDialog(this, "Este producto ya esta registrado");
                }            
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        jtp.setSelectedIndex(0);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombosActionPerformed
        LimpiarDerivados();
        LimpiarTable();
        try {
            // TODO add your handling code here:
            ListarDerivados();
        } catch (SQLException ex) {
            Logger.getLogger(sistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jtp.setSelectedIndex(2);
    }//GEN-LAST:event_btnCombosActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jtfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyTyped
        // TODO add your handling code here:
        
        jtfCodigo.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent ke) {
               trs.setRowFilter(RowFilter.regexFilter(jtfCodigo.getText(), 0));
            }
        });
        trs = new TableRowSorter(modelo);
        jtableP.setRowSorter(trs);
    }//GEN-LAST:event_jtfCodigoKeyTyped

    private void jtablePMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablePMouseClicked
        // TODO add your handling code here:
        int fila = jtableP.rowAtPoint(evt.getPoint());
        jtfCodigo.setText(jtableP.getValueAt(fila, 0).toString());
        jtfNombre.setText(jtableP.getValueAt(fila, 1).toString());
        jtfDetalle.setText(jtableP.getValueAt(fila,2).toString());
        jcbUnidad.setSelectedIndex(Integer.parseInt(jtableP.getValueAt(fila,3).toString()));
        jtfPrecio.setText(jtableP.getValueAt(fila, 4).toString());
        jtfBase.setText(jtableP.getValueAt(fila,5).toString());
        
    }//GEN-LAST:event_jtablePMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(!"".equals(jtfCodigo.getText())){
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Estas seguro que desea eliminar este producto?");
            if (pregunta==0) {
                int id = Integer.parseInt(jtfCodigo.getText());
                pdb.eliminarP(id);
                LimpiarTable();
                LimpiarProductos();
            try {
                ListarProductos();
            } catch (SQLException ex) {
                Logger.getLogger(sistema.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDActionPerformed
        // TODO add your handling code here:
        int resultado=0;
        if(!"".equals(jcbProductos.getSelectedItem())){
                der.setNombre(String.valueOf(jcbProductos.getSelectedItem()));
                der.setCd(Integer.parseInt(""+codigos.get(jcbProductos.getSelectedIndex())));
       
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione un producto base");
            resultado =1;
        }
        if(Numeros(jtfCodigoD.getText())){
                der.setCderivado(Integer.parseInt(jtfCodigoD.getText()));
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese solo valores numericos como codigo de derivado");
            resultado =1;
        }
        if(("").equals(jtfNombreD.getText())){
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para el derivado");
            resultado =1;
        }
        else{
            der.setNderivado(jtfNombreD.getText());
        }
        if(Numeros(jtfPrecioD.getText())){
            if(!jtfPrecioD.getText().equals("")){
                der.setPrecio(Float.parseFloat(jtfPrecioD.getText()));
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese un precio correcto");
            resultado =1;
        }
        der.setDetalled(jtfDetalleD.getText());
        if(resultado==0){
                boolean res = ddb.agregarD(der);
                if(res){
                     JOptionPane.showMessageDialog(this, "Derivado agregado correctamente");
             LimpiarTable();
                LimpiarDerivados();
            try {
                ListarDerivados();
            } catch (SQLException ex) {
                Logger.getLogger(sistema.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
                else{
                              JOptionPane.showMessageDialog(this, "No existe este producto");
                }            
        }
        
    }//GEN-LAST:event_btnAgregarDActionPerformed

    private void btnEliminarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDActionPerformed
        // TODO add your handling code here:
         if(!"".equals(jtfCodigoD.getText())){
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Estas seguro que desea eliminar este producto?");
            if (pregunta==0) {
                int id = Integer.parseInt(jtfCodigoD.getText());
                ddb.eliminarD(id);
                LimpiarTable();
                LimpiarDerivados();
            try {
                ListarDerivados();
            } catch (SQLException ex) {
                Logger.getLogger(sistema.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        }
    }//GEN-LAST:event_btnEliminarDActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
       int resultado=0;
        float base;
        int cdproducto;
        String nombre;
        String detalle;
        int unidad;
        float precio;
        if(Numeros(jtfBase.getText())){
            if(Numeros(jtfBase.getText()) && Float.parseFloat(jtfBase.getText())<=1 && Float.parseFloat(jtfBase.getText())>0){
                base = Float.parseFloat(jtfBase.getText());
                pro.setBase(base);
            }
            else{
                JOptionPane.showMessageDialog(this, "Ingrese solo valores en el rango 0.1Kg - 1Kg");
                resultado =1;
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese solo valores numericos como valor base");
            resultado =1;
        }
        if(jtfNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para el producto");
            resultado =1;
        }
        else{
            nombre = jtfNombre.getText();
            pro.setName(nombre);
        }
        if(Numeros(jtfCodigo.getText())){
            if(Float.parseFloat(jtfCodigo.getText())!=0){
                cdproducto = Integer.parseInt(jtfCodigo.getText());
                pro.setCd(cdproducto);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "El codigo no es valido");
            resultado =1;
        }
        if(jcbUnidad.getSelectedItem().equals("-")){
            JOptionPane.showMessageDialog(this, "Ingrese una unidad de medida");
            resultado =1;
        }
        else{
            unidad = jcbUnidad.getSelectedIndex();
            pro.setUdm(unidad);
        }
        if(Numeros(jtfPrecio.getText())){
            if(!jtfPrecio.getText().equals("")){
                precio = Float.parseFloat(jtfPrecio.getText());
                pro.setPrecio(precio);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese un precio correcto");
            resultado =1;
        }
        detalle = jtfDetalle.getText();
        pro.setDetalle(detalle);
        if(resultado==0){
                boolean res = pdb.editarP(pro);
                if(res){
                     JOptionPane.showMessageDialog(this, "Producto agregado correctamente");
             LimpiarTable();
                LimpiarProductos();
            try {
                ListarProductos();
            } catch (SQLException ex) {
                Logger.getLogger(sistema.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
                else{
                              JOptionPane.showMessageDialog(this, "Este producto ya esta registrado");
                }            
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jtableDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableDMouseClicked
        // TODO add your handling code here:
        int fila = jtableD.rowAtPoint(evt.getPoint());
        jcbProductos.setSelectedItem(jtableD.getValueAt(fila,1).toString());
        jtfCodigoD.setText(jtableD.getValueAt(fila,2).toString());
        jtfNombreD.setText(jtableD.getValueAt(fila,3).toString());
        jtfDetalleD.setText(jtableD.getValueAt(fila, 4).toString());
        jtfPrecioD.setText(jtableD.getValueAt(fila,5).toString());
    }//GEN-LAST:event_jtableDMouseClicked

    private void btnEditarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDActionPerformed
        // TODO add your handling code here:
          int resultado=0;
        if(!"".equals(jcbProductos.getSelectedItem())){
                der.setNombre(String.valueOf(jcbProductos.getSelectedItem()));
                    der.setCd(Integer.parseInt(""+codigos.get(jcbProductos.getSelectedIndex())));
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione un producto base");
            resultado =1;
        }
        
        if(Numeros(jtfCodigoD.getText())){
                der.setCderivado(Integer.parseInt(jtfCodigoD.getText()));
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese solo valores numericos como codigo de derivado");
            resultado =1;
        }
        if(("").equals(jtfNombreD.getText())){
            JOptionPane.showMessageDialog(this, "Ingrese un nombre para el derivado");
            resultado =1;
        }
        else{
            der.setNderivado(jtfNombreD.getText());
        }
        if(Numeros(jtfPrecioD.getText())){
            if(!jtfPrecioD.getText().equals("")){
                der.setPrecio(Float.parseFloat(jtfPrecioD.getText()));
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese un precio correcto");
            resultado =1;
        }
        der.setDetalled(jtfDetalleD.getText());
        if(resultado==0){
                boolean res = ddb.editarD(der);
                if(res){
                     JOptionPane.showMessageDialog(this, "Derivado agregado correctamente");
                LimpiarTable();
                LimpiarDerivados();
            try {
                ListarDerivados();
            } catch (SQLException ex) {
                Logger.getLogger(sistema.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
                else{
                              JOptionPane.showMessageDialog(this, "Este producto ya esta registrado");
                }            
        }
    }//GEN-LAST:event_btnEditarDActionPerformed

    private void jcbProductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbProductosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbProductosItemStateChanged

    private void btnAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCActionPerformed
        // TODO add your handling code here:
        //AGREGAR DATOS DEL PRODUCTO COMPRADO A LA TABLA Y DESPUES REGISTRAR VENTA 
        if(!jtfCantidadC.getText().equals("")){
                String cod = jtfCodigoC.getText();
                String nombre = jtfNombreC.getText();
                float cant = Float.parseFloat(jtfCantidadC.getText());
                float precio = Float.parseFloat(jtfPrecioC.getText());
                float total = precio * cant;
                item = item +1;
                tmp = (DefaultTableModel) jtCompra.getModel();
                for (int i = 0; i < jtCompra.getRowCount(); i++) {
                    if (jtCompra.getValueAt(i, 0).equals(jtfNombreC.getText())) {
                        JOptionPane.showMessageDialog(null, "El producto ya esta registrado");
                        LimpiarCompra();
                        jtfCodigoC.requestFocus();
                        return;
                    }
            }
                ArrayList lista = new ArrayList();
                lista.add(item);
                lista.add(cod);
                lista.add(nombre);
                lista.add(cant);
                lista.add(precio);
                lista.add(total);
                Object[] o = new Object[5];
                o[0]= lista.get(1);
                 o[1]= lista.get(2);
                 o[2]= lista.get(3);
                 o[3]= lista.get(4);
                 o[4]= lista.get(5);
                 tmp.addRow(o);
                 jtCompra.setModel(tmp);
                 Total();
                 LimpiarCompra();
                 jtfCodigoC.requestFocus();
            }
            else{
            JOptionPane.showMessageDialog(null, "Ingresa la cantidad");
            }
    }//GEN-LAST:event_btnAgregarCActionPerformed

    private void jtfCantidadCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCantidadCKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAgregarC.doClick();
        }
    }//GEN-LAST:event_jtfCantidadCKeyPressed

    private void jcbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbProductosActionPerformed

    private void jtfCodigoCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoCKeyPressed
        // TODO add your handling code her
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        if(!"".equals(jtfCodigoC.getText())){
            int cod = Integer.parseInt(jtfCodigoC.getText().toString());
        pro = pdb.BuscarPro(cod);
            if (pro.getName() != null) {
                jtfNombreC.setText(""+pro.getName());
                jtfPrecioC.setText(""+pro.getPrecio());
                jtfCantidadC.requestFocus();
            }
            else{
           LimpiarCompra();
           jtfCodigoC.requestFocus();
            }
        }else{
        JOptionPane.showMessageDialog(null, "Ingrese el codigo de producto");
        jtfCodigoC.requestFocus();
        }
        
        }
    }//GEN-LAST:event_jtfCodigoCKeyPressed

    private void jtfEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEliminarCActionPerformed
        // TODO add your handling code here:
        modelo = (DefaultTableModel) jtCompra.getModel();
        modelo.removeRow(jtCompra.getSelectedRow());
        Total();
        jtfCodigoC.requestFocus();
    }//GEN-LAST:event_jtfEliminarCActionPerformed

    private void bntRegCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegCActionPerformed
        // TODO add your handling code here:
        RegistrarCompra();
        RegistrarDetalleC();
        ActualizarStock();
        LimpiarCompra();
        LimpiarTableC();
    }//GEN-LAST:event_bntRegCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistema().setVisible(true);
                
            }
        });
    }
    private static String rol(){
        String rol;
    if(database.rol==2){
        rol="Administrador";
        }
        else{
        rol="Vendedor";
        }
    return rol;
    }
    private boolean Numeros(String base){
    float num;
    try {
    num = Float.parseFloat(base);
    return true;
    }    catch(Exception e){
    return false;
    }    
    }
    private void ListarProductos() throws SQLException{
    ArrayList<Productos> ListaP = pdb.ListarProductos();
    modelo = (DefaultTableModel) jtableP.getModel();
    Object[] ob = new Object[7];
        for (int i = 0; i < ListaP.size(); i++) {
            ob[0] = ListaP.get(i).getCd();
            ob[1] = ListaP.get(i).getName();
            ob[2] = ListaP.get(i).getDetalle();
            ob[3] = ListaP.get(i).getUdm();
            ob[4] = ListaP.get(i).getPrecio();
            ob[5] = ListaP.get(i).getBase();
            ob[6] = ListaP.get(i).getStock();
            modelo.addRow(ob);
        }
        jtableP.setModel(modelo);
    }
    private void ListarDerivados() throws SQLException{
    ArrayList<Derivados> ListaD = ddb.ListarProductosD();
    modelo = (DefaultTableModel) jtableD.getModel();
    Object[] ob = new Object[6];
        for (int i = 0; i < ListaD.size(); i++) {
            ob[0] = ListaD.get(i).getCd();
            ob[1] = ListaD.get(i).getNombre();
            ob[2] = ListaD.get(i).getCderivado();
            ob[3] = ListaD.get(i).getNderivado();
            ob[4] = ListaD.get(i).getDetalled();
            ob[5] = ListaD.get(i).getPrecio();
            modelo.addRow(ob);
        }
        jtableD.setModel(modelo);
    }
    private void LimpiarTable(){
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
        }
    }
    private void LimpiarTableC(){
    for (int i = 0; i < tmp.getRowCount(); i++) {
            tmp.removeRow(i);
            i=i-1;
        }
    }
    private void LimpiarProductos(){
    jtfCodigo.setText("");
    jtfNombre.setText(null);
    jtfDetalle.setText(null);
    jcbUnidad.setSelectedItem(null);
    jtfPrecio.setText(null);
    jtfBase.setText("1");
    jtfBase.setEnabled(false);
    jcbBase.setSelected(false);
    
    }
    private void LimpiarDerivados(){
    jcbProductos.setSelectedIndex(0);
    jtfCodigoD.setText("");
    jtfNombreD.setText("");
    jtfDetalleD.setText("");
    jtfPrecioD.setText("");
    }
    private void RegistrarCompra(){
        
     String vendedor = jlbUsuario.getText();
     Float totalC = Float.parseFloat(jtfTotalC.getText());
        c.setTotal(totalC);
        c.setVendedor(vendedor);
        cdb.registrarCompra(c);
    }
    private void Total(){
        totalpagar=0;
        int numFila = jtCompra.getRowCount();
        for (int i = 0; i < numFila; i++) {
            float cal = Float.parseFloat(""+jtCompra.getModel().getValueAt(i, 4));
            totalpagar = totalpagar+cal;
        }
        jtfTotalC.setText(""+String.format("%.2f",totalpagar));
    }
    private void LimpiarCompra(){
    jtfNombreC.setText("");
    jtfCodigoC.setText("");
    jtfCantidadC.setText("");
    jtfPrecioC.setText("");
    jtfTotalC.setText("");
    }
    private void RegistrarDetalleC(){
        int id = cdb.idVenta();
        for (int i = 0; i < jtCompra.getRowCount(); i++) {
            int cod = Integer.parseInt(jtCompra.getValueAt(i, 0).toString());
            Float cant = Float.parseFloat(jtCompra.getValueAt(i, 2).toString());
            Float pre = Float.parseFloat(jtCompra.getValueAt(i, 3).toString());
            cd.setCdproducto(cod);
            cd.setCantidad(cant);
            cd.setPrecio(pre);
            cd.setCdcompra(id);
            cdb.registarDetalleC(cd);
        }
    }
    private void ActualizarStock(){
        for (int i = 0; i < jtCompra.getRowCount(); i++) {
            int cod  = Integer.parseInt(jtCompra.getValueAt(i, 0).toString());
            float cant = Float.parseFloat(jtCompra.getValueAt(i, 2).toString());
            pro = pdb.BuscarPro(cod);
            float actual = pro.getStock()+cant;
            cdb.actualizar(cant, cod);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRegC;
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarC;
    private javax.swing.JButton btnAgregarD;
    private javax.swing.JButton btnCombos;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarD;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarD;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JCheckBox jcbBase;
    private javax.swing.JComboBox<String> jcbProductos;
    private javax.swing.JComboBox<String> jcbUnidad;
    private javax.swing.JLabel jlbFecha;
    private javax.swing.JLabel jlbRol;
    private javax.swing.JLabel jlbSeccion;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JTable jtCompra;
    private javax.swing.JTable jtableD;
    private javax.swing.JTable jtableP;
    private javax.swing.JTextField jtfBase;
    private javax.swing.JTextField jtfCantidadC;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfCodigoC;
    private javax.swing.JTextField jtfCodigoD;
    private javax.swing.JTextField jtfDetalle;
    private javax.swing.JTextField jtfDetalleD;
    private javax.swing.JButton jtfEliminarC;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNombreC;
    private javax.swing.JTextField jtfNombreD;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfPrecioC;
    private javax.swing.JTextField jtfPrecioD;
    private javax.swing.JTextField jtfTotalC;
    private javax.swing.JTabbedPane jtp;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
